---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jis-cluster
  region: us-east-2

# other cluster config ...

gitops:
  flux:
    gitProvider: github      # required. options are github, gitlab or git
    flags:                   # required. arbitrary map[string]string for all flux args.
    # these args are not controlled by eksctl. see https://fluxcd.io/docs/get-started/ for all available flags
      owner: "jishoy-cloudjournee"
      repository: "EKS"
     #private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "clusters/jis-cluster"
     #team: "team1,team2"
  
