---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: jiss
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/jishoy-cloudjournee/EKS.git

